name: ci

permissions:
  contents: read

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build (node v${{ matrix.node }} ${{ matrix.os }})
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13, macos-15 ]
        node: [ 18, 20 ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test
